server:
  port: 4000

csv:
  path: "/src/main/resources/flightdata.csv"

spring:
  datasource:
    url: "jdbc:h2:mem:flightdb"
    driverClassName: "org.h2.Driver"
    username: "admin"
    password:

  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
